"""Atualização do modelo Asset

Revision ID: 6b1fa2fdbf41
Revises: 
Create Date: 2025-03-31 15:33:42.488236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1fa2fdbf41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('localizacao', sa.String(length=100), nullable=True),
    sa.Column('centro_custos', sa.String(length=50), nullable=True),
    sa.Column('afo', sa.String(length=20), nullable=True),
    sa.Column('empenho', sa.String(length=20), nullable=True),
    sa.Column('processo_licitatorio', sa.String(length=30), nullable=True),
    sa.Column('danfe', sa.String(length=44), nullable=True),
    sa.Column('data_entrada', sa.DateTime(), nullable=True),
    sa.Column('data_danfe', sa.DateTime(), nullable=True),
    sa.Column('codigo_despesa', sa.String(length=10), nullable=True),
    sa.Column('valor_bem', sa.Float(), nullable=True),
    sa.Column('fornecedor', sa.String(length=100), nullable=True),
    sa.Column('numero_patrimonio', sa.String(length=50), nullable=True),
    sa.Column('numero_serial', sa.String(length=50), nullable=True),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('origem', sa.String(length=100), nullable=True),
    sa.Column('destino', sa.String(length=100), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=True),
    sa.Column('matricula_responsavel', sa.String(length=20), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset')
    # ### end Alembic commands ###
