"""Add MovimentoViatura table

Revision ID: 9d2c84a14360
Revises: a37e236c81f8
Create Date: 2025-05-27 12:18:54.731138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d2c84a14360'
down_revision = 'a37e236c81f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimento_viatura',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('data_movimento', sa.Date(), nullable=False),
    sa.Column('unidade', sa.String(length=100), nullable=False),
    sa.Column('ordem_servico', sa.String(length=50), nullable=True),
    sa.Column('hora_entrada', sa.Time(), nullable=False),
    sa.Column('hora_saida', sa.Time(), nullable=True),
    sa.Column('veiculo_tipo', sa.String(length=50), nullable=False),
    sa.Column('placa_veiculo', sa.String(length=10), nullable=False),
    sa.Column('condutor_nome', sa.String(length=100), nullable=False),
    sa.Column('tipo_movimentacao', sa.String(length=50), nullable=False),
    sa.Column('detalhe_movimentacao', sa.String(length=255), nullable=True),
    sa.Column('responsavel_atendimento', sa.String(length=100), nullable=False),
    sa.Column('data_registro_sistema', sa.DateTime(), nullable=True),
    sa.Column('ultima_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimento_viatura')
    # ### end Alembic commands ###
