"""Adicionando coluna ultima_atualizacao

Revision ID: a37e236c81f8
Revises: 6b1fa2fdbf41
Create Date: 2025-04-02 20:35:47.437874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37e236c81f8'
down_revision = '6b1fa2fdbf41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultima_atualizacao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('ultima_atualizacao')

    # ### end Alembic commands ###
